slam_toolbox:
  ros__parameters:
    # Plugin params
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None

    # ROS Parameters - Physical robot specific settings
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    scan_topic: /scan
    use_map_saver: true
    mode: mapping # set to mapping for creating maps
    map_file_name: robot_killer/maps/auto_saved_map
    map_start_pose: [0.0, 0.0, 0.0]
    
    # Physical robot params - adjusted for real hardware
    debug_logging: false
    throttle_scans: 1
    transform_publish_period: 0.02 #if 0 never publishes odometry
    map_update_interval: 3.0  # More frequent updates for physical robot
    resolution: 0.05
    max_laser_range: 12.0  # Reduced for more reliable physical measurements
    minimum_time_interval: 0.2  # More frequent updates
    transform_timeout: 0.5  # Increased for physical robot reliability
    tf_buffer_duration: 30.0
    stack_size_to_use: 40000000 #program needs a larger stack size to serialize large maps
    enable_interactive_mode: true  # Enable interactive mode for map saving

    # Physical robot scan matching
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.2  # More sensitive for physical robot
    minimum_travel_heading: 0.2  # More sensitive for physical robot
    scan_buffer_size: 10
    scan_buffer_maximum_scan_distance: 10.0
    link_match_minimum_response_fine: 0.15  # Adjusted for physical sensor noise
    link_scan_maximum_distance: 2.0  # Increased for better matching
    loop_search_maximum_distance: 5.0  # Wider search for loop closures
    do_loop_closing: true 
    loop_match_minimum_chain_size: 8  # Reduced for easier loop closing
    loop_match_maximum_variance_coarse: 3.0  
    loop_match_minimum_response_coarse: 0.3  # Adjusted for physical noise
    loop_match_minimum_response_fine: 0.4  # Adjusted for physical noise

    # Correlation Parameters - Correlation Parameters
    correlation_search_space_dimension: 0.6  # Increased for physical robot
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.1 

    # Correlation Parameters - Loop Closure Parameters
    loop_search_space_dimension: 8.0
    loop_search_space_resolution: 0.05
    loop_search_space_smear_deviation: 0.03

    # Scan Matcher Parameters
    distance_variance_penalty: 0.6  # Adjusted for physical sensors
    angle_variance_penalty: 1.2  # Adjusted for physical sensors

    fine_search_angle_offset: 0.00349  
    coarse_search_angle_offset: 0.349   
    coarse_angle_resolution: 0.0349    
    minimum_angle_penalty: 0.9
    minimum_distance_penalty: 0.5
    use_response_expansion: true 